"""Lightweight evaluation for the Phase 3 DOTA-v1.0 OBB model.

Unlike the VisDrone axis-aligned-box track, this needs no separate pycocotools
pipeline: model.val() already reports rotated-IoU OBB mAP directly. This script
just runs that validation locally (reproducing the Colab-reported numbers on the
same machine) and saves a couple of representative prediction overlays showing
genuinely rotated boxes, for the README's supplementary OBB section.

Usage:
    python scripts/evaluate_dota_obb.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import yaml
from ultralytics import YOLO

CLASS_NAMES = [
    "plane", "ship", "storage tank", "baseball diamond", "tennis court",
    "basketball court", "ground track field", "harbor", "bridge",
    "large vehicle", "small vehicle", "helicopter", "roundabout",
    "soccer ball field", "swimming pool",
]
BRIDGE_ID = CLASS_NAMES.index("bridge")
SHIP_ID = CLASS_NAMES.index("ship")
HARBOR_ID = CLASS_NAMES.index("harbor")


def build_yaml(split_root: Path) -> Path:
    yaml_path = split_root / "dota_obb.yaml"
    data_yaml = {
        "path": str(split_root), "train": "images/train", "val": "images/val",
        "names": dict(enumerate(CLASS_NAMES)),
    }
    yaml_path.write_text(yaml.safe_dump(data_yaml, sort_keys=False), encoding="utf-8")
    return yaml_path


def pick_representative_images(split_root: Path) -> dict[str, Path]:
    """Scan GT labels (not predictions) for a dense scene and a bridge scene."""
    img_dir = split_root / "images" / "val"
    lbl_dir = split_root / "labels" / "val"

    # "dense" picks the most ship/harbor instances specifically (not just most
    # objects overall) -- a 300-small-vehicle parking lot is dense but produces an
    # unreadable wall of overlapping labels; ships/harbors are bigger and stay
    # legible even in a crowded scene.
    best_dense: tuple[int, Path | None] = (0, None)
    best_bridge: tuple[int, Path | None] = (0, None)  # bridge instance count, for the most-bridge-heavy tile
    for lbl_path in lbl_dir.glob("*.txt"):
        lines = lbl_path.read_text().splitlines()
        classes = [int(line.split()[0]) for line in lines if line.split()]
        n_ship_harbor = sum(1 for c in classes if c in (SHIP_ID, HARBOR_ID))
        if n_ship_harbor > best_dense[0]:
            img_path = img_dir / (lbl_path.stem + ".jpg")
            if img_path.exists():
                best_dense = (n_ship_harbor, img_path)
        n_bridge = classes.count(BRIDGE_ID)
        if n_bridge > best_bridge[0]:
            img_path = img_dir / (lbl_path.stem + ".jpg")
            if img_path.exists():
                best_bridge = (n_bridge, img_path)

    picks = {}
    if best_dense[1] is not None:
        picks["dense"] = best_dense[1]
    if best_bridge[1] is not None:
        picks["bridge"] = best_bridge[1]
    return picks


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--weights", type=Path, default=Path("weights/yolo26s_dota_1024.pt"))
    parser.add_argument("--split-root", type=Path, default=Path.home() / "datasets" / "DOTAv1-split")
    parser.add_argument("--imgsz", type=int, default=1024)
    parser.add_argument("--conf", type=float, default=0.25)
    parser.add_argument("--out", type=Path, default=Path("reports/dota_obb_evaluation.md"))
    parser.add_argument("--figures-dir", type=Path, default=Path("reports/figures"))
    args = parser.parse_args()

    split_root = args.split_root.expanduser()
    data_yaml = build_yaml(split_root)

    model = YOLO(str(args.weights))
    metrics = model.val(data=str(data_yaml), imgsz=args.imgsz, split="val")

    args.figures_dir.mkdir(parents=True, exist_ok=True)
    picks = pick_representative_images(split_root)
    saved_figs = {}
    for tag, img_path in picks.items():
        r = model.predict(str(img_path), imgsz=args.imgsz, conf=args.conf, verbose=False)[0]
        out_path = args.figures_dir / f"dota_obb_{tag}_{img_path.stem}.jpg"
        r.save(str(out_path))
        n_det = len(r.obb) if r.obb is not None else 0
        saved_figs[tag] = (out_path, n_det)
        print(f"saved {out_path} ({n_det} detections @ conf>={args.conf})")

    names = metrics.names
    ap50 = metrics.box.ap50  # per-class AP50, aligned with metrics.ap_class_index
    ap5095 = metrics.box.maps  # per-class AP50-95 over ALL classes (0 for absent)
    ap_class_index = metrics.box.ap_class_index

    lines = ["# DOTA-v1.0 OBB evaluation (Phase 3, yolo26s-obb, imgsz=1024)", ""]
    lines.append(
        "Generated by `scripts/evaluate_dota_obb.py`. Uses ultralytics' built-in "
        "rotated-IoU OBB metrics via `model.val()` directly -- no separate "
        "pycocotools pipeline needed here, unlike the VisDrone axis-aligned-box track."
    )
    lines.append("")
    lines.append(
        f"**Training note**: two independent full runs (patience=20 stopping at "
        f"epoch 21, and a clean restart with patience=30 stopping at epoch 31) "
        f"both converged to the exact same result -- fitness peaked at epoch 1 "
        f"(the DOTAv1-pretrained starting checkpoint) and was never beaten by "
        f"further fine-tuning. Reported here as the accepted, reproducible result "
        f"rather than a still-improving intermediate checkpoint."
    )
    lines.append("")
    lines.append("## Aggregate metrics (val split, 5,297 tiles)")
    lines.append("")
    lines.append(f"- **mAP50**: {metrics.box.map50:.4f}")
    lines.append(f"- **mAP50-95**: {metrics.box.map:.4f}")
    lines.append(f"- **Precision**: {metrics.box.mp:.4f}")
    lines.append(f"- **Recall**: {metrics.box.mr:.4f}")
    lines.append("")
    lines.append("## Per-class AP")
    lines.append("")
    lines.append("| class | AP50 | AP50-95 |")
    lines.append("|-------|------|---------|")
    for i, cid in enumerate(ap_class_index):
        cname = names[int(cid)]
        lines.append(f"| {cname} | {ap50[i]:.3f} | {ap5095[i]:.3f} |")
    lines.append("")

    if saved_figs:
        lines.append("## Representative predictions (rotated boxes)")
        lines.append("")
        for tag, (path, n_det) in saved_figs.items():
            label = "Dense scene" if tag == "dense" else "Bridge scene"
            lines.append(f"**{label}** ({n_det} detections @ conf>={args.conf}):")
            lines.append("")
            lines.append(f"![{label}]({path.relative_to('reports').as_posix()})")
            lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nwrote {args.out}")
    print(f"mAP50={metrics.box.map50:.4f}  mAP50-95={metrics.box.map:.4f}")


if __name__ == "__main__":
    main()
